//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocks.Wasabee.Mobile.Core.Resources.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocks.Wasabee.Mobile.Core.Resources.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Teams.
        /// </summary>
        internal static string Dialog_Warning_GoToTeamsList {
            get {
                return ResourceManager.GetString("Dialog_Warning_GoToTeamsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OP&apos;s available.
        /// </summary>
        internal static string Dialog_Warning_NoOpsAvailable {
            get {
                return ResourceManager.GetString("Dialog_Warning_NoOpsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of your teams has been set to share your location. Go to Teams list and enable at least one team..
        /// </summary>
        internal static string Dialog_Warning_NoTeamSharingEnabled {
            get {
                return ResourceManager.GetString("Dialog_Warning_NoTeamSharingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions required.
        /// </summary>
        internal static string Dialog_Warning_PermissionsRequired {
            get {
                return ResourceManager.GetString("Dialog_Warning_PermissionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available OP&apos;s :.
        /// </summary>
        internal static string Dialogs_Title_AvailableOpsList {
            get {
                return ResourceManager.GetString("Dialogs_Title_AvailableOpsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation permission is required !.
        /// </summary>
        internal static string Dialogs_Warning_LocationPermissionRequired {
            get {
                return ResourceManager.GetString("Dialogs_Warning_LocationPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the live location sharing, please set the permission to &apos;Allow all the time&apos;..
        /// </summary>
        internal static string Dialogs_Warning_SetLocationPermissionsAllTheTime {
            get {
                return ResourceManager.GetString("Dialogs_Warning_SetLocationPermissionsAllTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Global_Add {
            get {
                return ResourceManager.GetString("Global_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured, please retry.
        /// </summary>
        internal static string Global_ErrorOccuredPleaseRetry {
            get {
                return ResourceManager.GetString("Global_ErrorOccuredPleaseRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet, please verify your network access.
        /// </summary>
        internal static string Global_NoInternet {
            get {
                return ResourceManager.GetString("Global_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Global_Ok {
            get {
                return ResourceManager.GetString("Global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Global_Version {
            get {
                return ResourceManager.GetString("Global_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Menu_Button_ChangeOp {
            get {
                return ResourceManager.GetString("Menu_Button_ChangeOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Menu_Button_Logout {
            get {
                return ResourceManager.GetString("Menu_Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Menu_Button_RefreshOps {
            get {
                return ResourceManager.GetString("Menu_Button_RefreshOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Map.
        /// </summary>
        internal static string Menu_Item_OperationMap {
            get {
                return ResourceManager.GetString("Menu_Item_OperationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Operations.
        /// </summary>
        internal static string Menu_Item_OperationsList {
            get {
                return ResourceManager.GetString("Menu_Item_OperationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Menu_Item_Profile {
            get {
                return ResourceManager.GetString("Menu_Item_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Item_Settings {
            get {
                return ResourceManager.GetString("Menu_Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string Menu_Item_Teams {
            get {
                return ResourceManager.GetString("Menu_Item_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP :.
        /// </summary>
        internal static string Menu_Label_CurrentOp {
            get {
                return ResourceManager.GetString("Menu_Label_CurrentOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server :.
        /// </summary>
        internal static string Menu_Label_CurrentServer {
            get {
                return ResourceManager.GetString("Menu_Label_CurrentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR loading OP.
        /// </summary>
        internal static string Menu_Label_ErrorLoadingOp {
            get {
                return ResourceManager.GetString("Menu_Label_ErrorLoadingOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location sharing :.
        /// </summary>
        internal static string Menu_Label_LocationSharing {
            get {
                return ResourceManager.GetString("Menu_Label_LocationSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any local OP&apos;s stored.
        /// </summary>
        internal static string Menu_Label_NoLocalOpsStored {
            get {
                return ResourceManager.GetString("Menu_Label_NoLocalOpsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information comes from V and/or .rocks. If you have an UnverifiedAgent_ name, please ensure your .Rocks and V information is correct..
        /// </summary>
        internal static string Profile_Label_DataOrigin {
            get {
                return ResourceManager.GetString("Profile_Label_DataOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Profile_Label_Status {
            get {
                return ResourceManager.GetString("Profile_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V Status.
        /// </summary>
        internal static string Profile_Label_VStatus {
            get {
                return ResourceManager.GetString("Profile_Label_VStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile_Page_Title {
            get {
                return ResourceManager.GetString("Profile_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app system settings.
        /// </summary>
        internal static string Settings_Button_OpenSystemSettings {
            get {
                return ResourceManager.GetString("Settings_Button_OpenSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Anonymous Analytics.
        /// </summary>
        internal static string Settings_Label_AnonymousAnalytics {
            get {
                return ResourceManager.GetString("Settings_Label_AnonymousAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (this helps the developers improve Wasabee).
        /// </summary>
        internal static string Settings_Label_AnonymousAnalyticsHint {
            get {
                return ResourceManager.GetString("Settings_Label_AnonymousAnalyticsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch light/dark theme.
        /// </summary>
        internal static string Settings_Label_DarkMode {
            get {
                return ResourceManager.GetString("Settings_Label_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh FCM token.
        /// </summary>
        internal static string Settings_Label_RefreshFcmToken {
            get {
                return ResourceManager.GetString("Settings_Label_RefreshFcmToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send logs.
        /// </summary>
        internal static string Settings_Label_SendLogs {
            get {
                return ResourceManager.GetString("Settings_Label_SendLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personnal data are sent. You can include Wasabee data..
        /// </summary>
        internal static string Settings_Label_SendLogsHint {
            get {
                return ResourceManager.GetString("Settings_Label_SendLogsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Agents from any team on Map.
        /// </summary>
        internal static string Settings_Label_ShowAgentsFromAnyTeam {
            get {
                return ResourceManager.GetString("Settings_Label_ShowAgentsFromAnyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug messages.
        /// </summary>
        internal static string Settings_Label_ShowDebugToasts {
            get {
                return ResourceManager.GetString("Settings_Label_ShowDebugToasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasabee Webpage.
        /// </summary>
        internal static string Settings_Label_WasabeeWebpage {
            get {
                return ResourceManager.GetString("Settings_Label_WasabeeWebpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Settings_Section_About {
            get {
                return ResourceManager.GetString("Settings_Section_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Settings_Section_Application {
            get {
                return ResourceManager.GetString("Settings_Section_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc..
        /// </summary>
        internal static string Settings_Section_Miscellaneous {
            get {
                return ResourceManager.GetString("Settings_Section_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Settings_Section_Permissions {
            get {
                return ResourceManager.GetString("Settings_Section_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token updated.
        /// </summary>
        internal static string Settings_Toast_FcmtokenUpdated {
            get {
                return ResourceManager.GetString("Settings_Toast_FcmtokenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is beeing sent automatically.
        /// </summary>
        internal static string Settings_Toast_LogsAutomaticallySent {
            get {
                return ResourceManager.GetString("Settings_Toast_LogsAutomaticallySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any log files.
        /// </summary>
        internal static string Settings_Warning_NoLogs {
            get {
                return ResourceManager.GetString("Settings_Warning_NoLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the file to @fisher01 on Telegram.
        /// </summary>
        internal static string Settings_Warning_SendFileOverTelegram {
            get {
                return ResourceManager.GetString("Settings_Warning_SendFileOverTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t include !.
        /// </summary>
        internal static string Settings_Warning_SendLogs_NoDb {
            get {
                return ResourceManager.GetString("Settings_Warning_SendLogs_NoDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, include it !.
        /// </summary>
        internal static string Settings_Warning_SendLogs_WithDb {
            get {
                return ResourceManager.GetString("Settings_Warning_SendLogs_WithDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include local DB copy ? This will include ALL your teams and OPS related data, please take care !.
        /// </summary>
        internal static string Settings_Warning_SendLogsWithDatabase {
            get {
                return ResourceManager.GetString("Settings_Warning_SendLogsWithDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #OpSec Warning !.
        /// </summary>
        internal static string Settings_Warning_SendLogsWithDatabase_Title {
            get {
                return ResourceManager.GetString("Settings_Warning_SendLogsWithDatabase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permissions are required !.
        /// </summary>
        internal static string Settings_Warning_StoragePermissionsNeeded {
            get {
                return ResourceManager.GetString("Settings_Warning_StoragePermissionsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✗   Cancel.
        /// </summary>
        internal static string SignIn_Button_Cancel {
            get {
                return ResourceManager.GetString("SignIn_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account.
        /// </summary>
        internal static string SignIn_Button_ChangeAccount {
            get {
                return ResourceManager.GetString("SignIn_Button_ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change server.
        /// </summary>
        internal static string SignIn_Button_ChangeServer {
            get {
                return ResourceManager.GetString("SignIn_Button_ChangeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓   Next.
        /// </summary>
        internal static string SignIn_Button_Next {
            get {
                return ResourceManager.GetString("SignIn_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use One Time Token.
        /// </summary>
        internal static string SignIn_Button_OneTimeToken {
            get {
                return ResourceManager.GetString("SignIn_Button_OneTimeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string SignIn_Button_Retry {
            get {
                return ResourceManager.GetString("SignIn_Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓   Validate.
        /// </summary>
        internal static string SignIn_Button_Validate {
            get {
                return ResourceManager.GetString("SignIn_Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        internal static string SignIn_Button_WithGoogle {
            get {
                return ResourceManager.GetString("SignIn_Button_WithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the token :.
        /// </summary>
        internal static string SignIn_Label_EnterToken {
            get {
                return ResourceManager.GetString("SignIn_Label_EnterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google login failed !.
        /// </summary>
        internal static string SignIn_Label_ErrorMsg_GoogleError {
            get {
                return ResourceManager.GetString("SignIn_Label_ErrorMsg_GoogleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string SignIn_Label_ErrorMsg_Internal {
            get {
                return ResourceManager.GetString("SignIn_Label_ErrorMsg_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Wasabee OPs data.
        /// </summary>
        internal static string SignIn_Label_ErrorMsg_LoadingOpsData {
            get {
                return ResourceManager.GetString("SignIn_Label_ErrorMsg_LoadingOpsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasabee login failed !.
        /// </summary>
        internal static string SignIn_Label_ErrorMsg_WasabeeFail {
            get {
                return ResourceManager.GetString("SignIn_Label_ErrorMsg_WasabeeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application loading....
        /// </summary>
        internal static string SignIn_Label_LoadingStep_AppLoading {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_AppLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting &apos;{0}&apos; Wasabee server....
        /// </summary>
        internal static string SignIn_Label_LoadingStep_ContactingServer {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_ContactingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google login success....
        /// </summary>
        internal static string SignIn_Label_LoadingStep_GoogleSuccess {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_GoogleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvesting beehive,.
        /// </summary>
        internal static string SignIn_Label_LoadingStep_LoadingData {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string SignIn_Label_LoadingStep_LoggingIn {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your server :.
        /// </summary>
        internal static string SignIn_Label_LoadingStep_SelectServer {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose token&apos;s server :.
        /// </summary>
        internal static string SignIn_Label_LoadingStep_SelectServerToken {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_SelectServerToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        internal static string SignIn_Label_LoadingStep_WelcomeAgent {
            get {
                return ResourceManager.GetString("SignIn_Label_LoadingStep_WelcomeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to Internet over Wi-Fi or cellular network to use this application.
        /// </summary>
        internal static string SignIn_Label_NoInternet {
            get {
                return ResourceManager.GetString("SignIn_Label_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any assigned team or operation, contact your Operator before using Wasabee Mobile !.
        /// </summary>
        internal static string SignIn_Label_NoTeamsOrOperation {
            get {
                return ResourceManager.GetString("SignIn_Label_NoTeamsOrOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string SignIn_Label_PleaseWait {
            get {
                return ResourceManager.GetString("SignIn_Label_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my choice (quick login if enabled).
        /// </summary>
        internal static string SignIn_Label_RememberServerChoice {
            get {
                return ResourceManager.GetString("SignIn_Label_RememberServerChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please !.
        /// </summary>
        internal static string SignIn_Label_Warning {
            get {
                return ResourceManager.GetString("SignIn_Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Agent.
        /// </summary>
        internal static string TeamDetail_Button_AddAgent {
            get {
                return ResourceManager.GetString("TeamDetail_Button_AddAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        internal static string TeamDetail_Button_RenameTeam {
            get {
                return ResourceManager.GetString("TeamDetail_Button_RenameTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent name.
        /// </summary>
        internal static string TeamDetail_Prompt_AddAgentTitle {
            get {
                return ResourceManager.GetString("TeamDetail_Prompt_AddAgentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in the team !.
        /// </summary>
        internal static string TeamDetail_Warning_AgentAlreadyInTeam {
            get {
                return ResourceManager.GetString("TeamDetail_Warning_AgentAlreadyInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent not found.
        /// </summary>
        internal static string TeamDetail_Warning_AgentNotFound {
            get {
                return ResourceManager.GetString("TeamDetail_Warning_AgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &apos;{0}&apos; from the team ?.
        /// </summary>
        internal static string TeamDetail_Warning_RemoveAgent {
            get {
                return ResourceManager.GetString("TeamDetail_Warning_RemoveAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change team name.
        /// </summary>
        internal static string Teams_Prompt_ChangeTeamNameTitle {
            get {
                return ResourceManager.GetString("Teams_Prompt_ChangeTeamNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while loading your teams.
        /// </summary>
        internal static string TeamsList_Label_ErrorLoadingTeams {
            get {
                return ResourceManager.GetString("TeamsList_Label_ErrorLoadingTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string TeamsList_Page_Title {
            get {
                return ResourceManager.GetString("TeamsList_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location sharing state changed for team {0}.
        /// </summary>
        internal static string TeamsList_Toast_LocationSharingStateChanged {
            get {
                return ResourceManager.GetString("TeamsList_Toast_LocationSharingStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted team &apos;{0}&apos;.
        /// </summary>
        internal static string TeamsList_Toast_TeamDeleted {
            get {
                return ResourceManager.GetString("TeamsList_Toast_TeamDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State can&apos;t be changed, please try again.
        /// </summary>
        internal static string TeamsList_Toast_Warning_CantChangeState {
            get {
                return ResourceManager.GetString("TeamsList_Toast_Warning_CantChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger zone.
        /// </summary>
        internal static string TeamsList_Warning_DeleteTeamTitle {
            get {
                return ResourceManager.GetString("TeamsList_Warning_DeleteTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm one last time before deletion.
        /// </summary>
        internal static string TeamsList_Warning_TeamDeleteLastWarning {
            get {
                return ResourceManager.GetString("TeamsList_Warning_TeamDeleteLastWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you REALLY sure ?.
        /// </summary>
        internal static string TeamsList_Warning_TeamDeleteSecondWarning {
            get {
                return ResourceManager.GetString("TeamsList_Warning_TeamDeleteSecondWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to delete the team &apos;{0}&apos;. Are you sure ?.
        /// </summary>
        internal static string TeamsList_Warning_TeamWillDelete {
            get {
                return ResourceManager.GetString("TeamsList_Warning_TeamWillDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OPs are loading in background.
        /// </summary>
        internal static string Toasts_LoadingOpsInBackground {
            get {
                return ResourceManager.GetString("Toasts_LoadingOpsInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPs loaded succesfully.
        /// </summary>
        internal static string Toasts_LoadingOpsSuccess {
            get {
                return ResourceManager.GetString("Toasts_LoadingOpsSuccess", resourceCulture);
            }
        }
    }
}
