//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocks.Wasabee.Mobile.Core.Resources.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocks.Wasabee.Mobile.Core.Resources.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account.
        /// </summary>
        internal static string SignIn_Button_ChangeAccount {
            get {
                return ResourceManager.GetString("SignIn_Button_ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change server.
        /// </summary>
        internal static string SignIn_Button_ChangeServer {
            get {
                return ResourceManager.GetString("SignIn_Button_ChangeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use One Time Token.
        /// </summary>
        internal static string SignIn_Button_OneTimeToken {
            get {
                return ResourceManager.GetString("SignIn_Button_OneTimeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string SignIn_Button_Retry {
            get {
                return ResourceManager.GetString("SignIn_Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        internal static string SignIn_Button_WithGoogle {
            get {
                return ResourceManager.GetString("SignIn_Button_WithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the token :.
        /// </summary>
        internal static string SignIn_Label_EnterToken {
            get {
                return ResourceManager.GetString("SignIn_Label_EnterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to Internet over Wi-Fi or cellular network to use this application.
        /// </summary>
        internal static string SignIn_Label_NoInternet {
            get {
                return ResourceManager.GetString("SignIn_Label_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my choice (quick login if enabled).
        /// </summary>
        internal static string SignIn_Label_RememberServerChoice {
            get {
                return ResourceManager.GetString("SignIn_Label_RememberServerChoice", resourceCulture);
            }
        }
    }
}
